# Generated by Django 5.2.4 on 2025-09-25 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_type', models.CharField(choices=[('mission', 'Mission Statement'), ('vision', 'Vision Statement'), ('approach', 'Our Approach'), ('philosophy', 'Our Philosophy'), ('custom', 'Custom Section')], default='custom', help_text='Type of content section', max_length=20)),
                ('title', models.CharField(help_text='Section title', max_length=200)),
                ('content', models.TextField(help_text='Section content (HTML supported)')),
                ('image', models.ImageField(blank=True, help_text='Optional section image', null=True, upload_to='about/content/')),
                ('alt_text', models.CharField(blank=True, help_text='Alt text for image', max_length=200)),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order (lower numbers first)')),
                ('is_active', models.BooleanField(default=True, help_text='Show this content section')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'About Content Section',
                'verbose_name_plural': 'About Content Sections',
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='AboutHero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='About chobighar', help_text="Hero section title (e.g., 'About chobighar')", max_length=200)),
                ('subtitle', models.TextField(help_text='Hero section subtitle/description')),
                ('hero_image', models.ImageField(help_text='Hero section background image (full width, 50vh height recommended)', upload_to='about/hero/')),
                ('alt_text', models.CharField(default='About chobighar hero image', help_text='Alt text for accessibility', max_length=200)),
                ('is_active', models.BooleanField(default=True, help_text='Show this hero section')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'About Hero Section',
                'verbose_name_plural': 'About Hero Sections',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AboutStory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Our Story', help_text="Story section title (e.g., 'Our Story')", max_length=200)),
                ('content', models.TextField(help_text='Main story content (HTML supported)')),
                ('story_image', models.ImageField(help_text='Story section image', upload_to='about/story/')),
                ('alt_text', models.CharField(default='Our story image', help_text='Alt text for story image', max_length=200)),
                ('happy_couples', models.PositiveIntegerField(default=500, help_text='Number of happy couples served')),
                ('years_experience', models.PositiveIntegerField(default=5, help_text='Years of experience')),
                ('photos_captured', models.CharField(default='50k+', help_text="Number of photos captured (e.g., '50k+', '10000')", max_length=20)),
                ('is_active', models.BooleanField(default=True, help_text='Show this story section')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'About Story Section',
                'verbose_name_plural': 'About Story Sections',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AboutValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text="Value title (e.g., 'Excellence', 'Passion')", max_length=100)),
                ('description', models.TextField(help_text='Value description')),
                ('icon_type', models.CharField(choices=[('camera', 'Camera'), ('heart', 'Heart'), ('users', 'Users'), ('star', 'Star'), ('trophy', 'Trophy'), ('target', 'Target'), ('shield', 'Shield'), ('lightbulb', 'Lightbulb')], default='star', help_text='Icon to display with this value', max_length=20)),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order (lower numbers first)')),
                ('is_active', models.BooleanField(default=True, help_text='Show this value')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'About Value',
                'verbose_name_plural': 'About Values',
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Team member name', max_length=200)),
                ('position', models.CharField(help_text='Job position/title', max_length=200)),
                ('bio', models.TextField(blank=True, help_text='Short biography')),
                ('profile_image', models.ImageField(help_text='Team member profile photo (square aspect ratio recommended)', upload_to='about/team/')),
                ('alt_text', models.CharField(help_text='Alt text for profile image', max_length=200)),
                ('email', models.EmailField(blank=True, help_text='Email address (optional)', max_length=254)),
                ('phone', models.CharField(blank=True, help_text='Phone number (optional)', max_length=20)),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order (lower numbers first)')),
                ('is_active', models.BooleanField(default=True, help_text='Show this team member')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Team Member',
                'verbose_name_plural': 'Team Members',
                'ordering': ['order', 'created_at'],
            },
        ),
    ]
