# Generated by Django 5.2.4 on 2025-09-26 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aboutpage', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutstory',
            name='happy_couples',
        ),
        migrations.RemoveField(
            model_name='aboutstory',
            name='photos_captured',
        ),
        migrations.RemoveField(
            model_name='aboutstory',
            name='years_experience',
        ),
        migrations.AddField(
            model_name='abouthero',
            name='happy_couples',
            field=models.PositiveIntegerField(default=500, help_text='Number of happy couples served'),
        ),
        migrations.AddField(
            model_name='abouthero',
            name='photos_captured',
            field=models.CharField(default='50k+', help_text="Number of photos captured (e.g., '50k+', '10000')", max_length=20),
        ),
        migrations.AddField(
            model_name='abouthero',
            name='years_experience',
            field=models.PositiveIntegerField(default=5, help_text='Years of experience'),
        ),
    ]
