# Generated by Django 5.2.6 on 2025-09-25 20:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AchievementCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Achievement title', max_length=100)),
                ('count', models.PositiveIntegerField(help_text='Achievement count/number')),
                ('suffix', models.CharField(default='+', help_text='Suffix for the number (e.g., +, K, M)', max_length=10)),
                ('icon', models.CharField(choices=[('camera', 'Camera'), ('heart', 'Heart'), ('users', 'Users'), ('star', 'Star'), ('trophy', 'Trophy'), ('calendar', 'Calendar'), ('photo', 'Photo'), ('video', 'Video')], default='star', help_text='Icon for the achievement', max_length=100)),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order (lower numbers first)')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Achievement Counter',
                'verbose_name_plural': 'Achievement Counters',
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='ArtistryVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Video title', max_length=200)),
                ('description', models.TextField(help_text='Video description')),
                ('video_file', models.FileField(help_text='Video file (MP4 recommended)', upload_to='homepage/videos/')),
                ('thumbnail', models.ImageField(blank=True, help_text='Video thumbnail image', null=True, upload_to='homepage/video_thumbnails/')),
                ('background_image', models.ImageField(help_text='Background image for video section', upload_to='homepage/video_backgrounds/')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Artistry Video',
                'verbose_name_plural': 'Artistry Videos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Image title', max_length=200)),
                ('image', models.ImageField(help_text='Gallery image', upload_to='homepage/gallery/')),
                ('alt_text', models.CharField(help_text='Alt text for accessibility', max_length=200)),
                ('category', models.CharField(choices=[('wedding', 'Wedding'), ('portrait', 'Portrait'), ('event', 'Event'), ('prewedding', 'Pre-Wedding'), ('fashion', 'Fashion'), ('commercial', 'Commercial')], default='wedding', help_text='Image category', max_length=100)),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order (lower numbers first)')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Gallery Image',
                'verbose_name_plural': 'Gallery Images',
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='HeroSlide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Main slide title', max_length=200)),
                ('subtitle', models.CharField(help_text='Slide subtitle', max_length=300)),
                ('description', models.TextField(help_text='Slide description text')),
                ('background_image', models.ImageField(help_text='Background image for the slide', upload_to='homepage/hero/')),
                ('cta_text', models.CharField(default='Book Now', help_text='Call to action button text', max_length=50)),
                ('cta_link', models.URLField(blank=True, help_text='Call to action button link', null=True)),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order (lower numbers first)')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Hero Slide',
                'verbose_name_plural': 'Hero Slides',
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='HomepageSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_section_title', models.CharField(default='Capturing Your Beautiful Moments', help_text='Main title for hero section', max_length=200)),
                ('hero_section_subtitle', models.CharField(default='Professional Bengali Traditional Photography & Videography Services', help_text='Subtitle for hero section', max_length=300)),
                ('gallery_section_title', models.CharField(default='Captured Moments & Stories', help_text='Title for gallery section', max_length=200)),
                ('gallery_section_subtitle', models.CharField(default='Every frame tells a story, every moment becomes a memory', help_text='Subtitle for gallery section', max_length=300)),
                ('artistry_section_title', models.CharField(default='Experience Our Artistry', help_text='Title for artistry video section', max_length=200)),
                ('artistry_section_subtitle', models.CharField(default='Watch how we bring your vision to life', help_text='Subtitle for artistry video section', max_length=300)),
                ('achievements_section_title', models.CharField(default='Our Achievements', help_text='Title for achievements section', max_length=200)),
                ('testimonial_section_title', models.CharField(default='What Our Clients Say', help_text='Title for testimonials section', max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Homepage Settings',
                'verbose_name_plural': 'Homepage Settings',
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(help_text='Client name', max_length=100)),
                ('service', models.CharField(help_text='Service they used', max_length=100)),
                ('review_text', models.TextField(help_text='Review content')),
                ('rating', models.PositiveIntegerField(default=5, help_text='Rating out of 5 stars', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('client_image', models.ImageField(blank=True, help_text='Client photo', null=True, upload_to='homepage/client_photos/')),
                ('review_date', models.DateField(help_text='Date of the review')),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order (lower numbers first)')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Review',
                'verbose_name_plural': 'Reviews',
                'ordering': ['order', '-review_date'],
            },
        ),
        migrations.CreateModel(
            name='VideoTestimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(help_text='Client name', max_length=100)),
                ('service', models.CharField(help_text='Service they used', max_length=100)),
                ('video_file', models.FileField(help_text='Testimonial video file (MP4 recommended)', upload_to='homepage/testimonial_videos/')),
                ('thumbnail', models.ImageField(help_text='Video thumbnail image', upload_to='homepage/testimonial_thumbnails/')),
                ('rating', models.PositiveIntegerField(default=5, help_text='Rating out of 5 stars', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('quote', models.TextField(blank=True, help_text='Brief quote from the testimonial')),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order (lower numbers first)')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Video Testimonial',
                'verbose_name_plural': 'Video Testimonials',
                'ordering': ['order', 'created_at'],
            },
        ),
    ]
