# Generated by Django 5.2.6 on 2025-09-25 20:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AchievementCounter',
        ),
        migrations.DeleteModel(
            name='ArtistryVideo',
        ),
        migrations.DeleteModel(
            name='GalleryImage',
        ),
        migrations.DeleteModel(
            name='Review',
        ),
        migrations.DeleteModel(
            name='VideoTestimonial',
        ),
        migrations.RemoveField(
            model_name='heroslide',
            name='background_image',
        ),
        migrations.RemoveField(
            model_name='heroslide',
            name='cta_link',
        ),
        migrations.RemoveField(
            model_name='heroslide',
            name='cta_text',
        ),
        migrations.RemoveField(
            model_name='heroslide',
            name='description',
        ),
        migrations.RemoveField(
            model_name='heroslide',
            name='subtitle',
        ),
        migrations.RemoveField(
            model_name='homepagesettings',
            name='achievements_section_title',
        ),
        migrations.RemoveField(
            model_name='homepagesettings',
            name='artistry_section_subtitle',
        ),
        migrations.RemoveField(
            model_name='homepagesettings',
            name='artistry_section_title',
        ),
        migrations.RemoveField(
            model_name='homepagesettings',
            name='gallery_section_subtitle',
        ),
        migrations.RemoveField(
            model_name='homepagesettings',
            name='gallery_section_title',
        ),
        migrations.RemoveField(
            model_name='homepagesettings',
            name='hero_section_subtitle',
        ),
        migrations.RemoveField(
            model_name='homepagesettings',
            name='hero_section_title',
        ),
        migrations.RemoveField(
            model_name='homepagesettings',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='homepagesettings',
            name='testimonial_section_title',
        ),
        migrations.AddField(
            model_name='heroslide',
            name='alt_text',
            field=models.CharField(default='chobighar Photography', help_text='Alt text for accessibility', max_length=200),
        ),
        migrations.AddField(
            model_name='heroslide',
            name='caption',
            field=models.CharField(blank=True, help_text='Optional caption text overlay (not used currently)', max_length=300),
        ),
        migrations.AddField(
            model_name='heroslide',
            name='image',
            field=models.ImageField(blank=True, help_text='Slider image (recommended: 1920x1080px or similar aspect ratio)', null=True, upload_to='homepage/slider/'),
        ),
        migrations.AddField(
            model_name='heroslide',
            name='link_url',
            field=models.URLField(blank=True, help_text='Optional link when slide is clicked (not used currently)'),
        ),
        migrations.AddField(
            model_name='homepagesettings',
            name='show_progress_bar',
            field=models.BooleanField(default=True, help_text='Show progress bar on slider'),
        ),
        migrations.AddField(
            model_name='homepagesettings',
            name='show_slider_arrows',
            field=models.BooleanField(default=True, help_text='Show navigation arrows on slider'),
        ),
        migrations.AddField(
            model_name='homepagesettings',
            name='show_slider_dots',
            field=models.BooleanField(default=True, help_text='Show dot indicators on slider'),
        ),
        migrations.AddField(
            model_name='homepagesettings',
            name='slider_auto_advance',
            field=models.BooleanField(default=True, help_text='Auto-advance slider slides'),
        ),
        migrations.AddField(
            model_name='homepagesettings',
            name='slider_interval',
            field=models.PositiveIntegerField(default=5000, help_text='Slide change interval in milliseconds (1000-15000)', validators=[django.core.validators.MinValueValidator(1000), django.core.validators.MaxValueValidator(15000)]),
        ),
        migrations.AlterField(
            model_name='heroslide',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Show this slide in the slider'),
        ),
        migrations.AlterField(
            model_name='heroslide',
            name='title',
            field=models.CharField(blank=True, help_text='Slide title (optional, for admin reference)', max_length=200),
        ),
    ]
