# Generated by Django 5.2.6 on 2025-09-25 21:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0002_delete_achievementcounter_delete_artistryvideo_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HomepageSettings',
        ),
    ]
