# Generated by Django 5.2.6 on 2025-09-25 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0004_galleryimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShowcaseImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='Showcase image', upload_to='homepage/showcase/')),
                ('alt_text', models.CharField(default='Chabighar Photography Showcase', help_text='Alt text for accessibility', max_length=200)),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order (lower numbers first)')),
                ('is_active', models.BooleanField(default=True, help_text='Show this image in the showcase')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Showcase Image',
                'verbose_name_plural': 'Showcase Images',
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.DeleteModel(
            name='GalleryImage',
        ),
    ]
