# Generated by Django 5.2.6 on 2025-09-25 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0005_showcaseimage_delete_galleryimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='TextTestimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Client name (e.g., 'Priya & Arjun Sharma')", max_length=200)),
                ('location', models.CharField(blank=True, help_text="Client location (e.g., 'Kolkata, Mumbai')", max_length=100)),
                ('event', models.CharField(blank=True, help_text="Event type (e.g., 'Wedding Photography', 'Pre-Wedding Shoot')", max_length=200)),
                ('date', models.CharField(blank=True, help_text="Event date (e.g., 'December 2024')", max_length=50)),
                ('image', models.ImageField(help_text='Client photo or event image', upload_to='testimonials/images/')),
                ('text', models.TextField(help_text='Testimonial text content')),
                ('rating', models.PositiveSmallIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=5, help_text='Rating from 1 to 5 stars')),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order (lower numbers first)')),
                ('is_active', models.BooleanField(default=True, help_text='Show this testimonial on website')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Text Testimonial',
                'verbose_name_plural': 'Text Testimonials',
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='VideoTestimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Client name (e.g., 'Dr. Rahman Ahmed')", max_length=200)),
                ('location', models.CharField(blank=True, help_text="Client location (e.g., 'Kolkata, Mumbai')", max_length=100)),
                ('event', models.CharField(blank=True, help_text="Event type (e.g., 'Wedding Photography', 'Pre-Wedding Shoot')", max_length=200)),
                ('date', models.CharField(blank=True, help_text="Event date (e.g., 'December 2024')", max_length=50)),
                ('video_file', models.FileField(help_text='Upload video testimonial file (MP4 recommended)', upload_to='testimonials/videos/')),
                ('thumbnail', models.ImageField(blank=True, help_text='Video thumbnail image', null=True, upload_to='testimonials/thumbnails/')),
                ('rating', models.PositiveSmallIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=5, help_text='Rating from 1 to 5 stars')),
                ('description', models.TextField(blank=True, help_text='Optional description of the testimonial')),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order (lower numbers first)')),
                ('is_active', models.BooleanField(default=True, help_text='Show this testimonial on website')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Video Testimonial',
                'verbose_name_plural': 'Video Testimonials',
                'ordering': ['order', 'created_at'],
            },
        ),
    ]
