# Generated by Django 5.2.6 on 2025-09-25 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0006_texttestimonial_videotestimonial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(help_text='The FAQ question', max_length=500)),
                ('answer', models.TextField(help_text='The detailed answer to the question')),
                ('category', models.CharField(choices=[('photography', 'Photography Services'), ('booking', 'Booking & Pricing'), ('destination', 'Destination Wedding'), ('delivery', 'Photo Delivery'), ('customization', 'Package Customization'), ('general', 'General Questions')], default='general', help_text='FAQ category for organization', max_length=50)),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order (lower numbers first)')),
                ('is_active', models.BooleanField(default=True, help_text='Show this FAQ on website')),
                ('keywords', models.CharField(blank=True, help_text='Keywords for search (comma separated)', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'FAQ',
                'verbose_name_plural': 'FAQs',
                'ordering': ['order', 'created_at'],
            },
        ),
    ]
