# Generated by Django 5.2.6 on 2025-09-25 22:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0007_faq'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faq',
            name='category',
        ),
    ]
