# Generated by Django 5.2.6 on 2025-09-25 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0008_remove_faq_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text="Achievement title (e.g., 'Happy Couples')", max_length=100)),
                ('count_value', models.DecimalField(decimal_places=1, help_text='The number to display (e.g., 500, 5.0, 98)', max_digits=10)),
                ('suffix', models.CharField(blank=True, help_text="Suffix for the number (e.g., '+', '%', 'K')", max_length=10)),
                ('description', models.CharField(help_text="Short description (e.g., 'Beautiful love stories captured')", max_length=200)),
                ('icon_type', models.CharField(choices=[('heart', 'Heart (Happy Couples)'), ('video', 'Video (Video Reviews)'), ('star', 'Star (Average Rating)'), ('check', 'Check (Client Satisfaction)'), ('camera', 'Camera (Photos Taken)'), ('award', 'Award (Awards Won)'), ('users', 'Users (Team Members)'), ('calendar', 'Calendar (Years Experience)')], default='star', help_text='Icon to display with this achievement', max_length=20)),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order (lower numbers first)')),
                ('is_active', models.BooleanField(default=True, help_text='Show this achievement on website')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Achievement',
                'verbose_name_plural': 'Achievements',
                'ordering': ['order', 'created_at'],
            },
        ),
    ]
