# Generated by Django 5.2.6 on 2025-09-25 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0009_add_achievement_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoShowcase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Wedding Cinematic Reel', help_text='Main title for the video showcase', max_length=200)),
                ('description', models.TextField(default='A glimpse into our wedding photography and videography excellence, capturing emotions that last forever', help_text='Description text below the title')),
                ('youtube_url', models.URLField(help_text='YouTube video URL (e.g., https://www.youtube.com/watch?v=VIDEO_ID)')),
                ('placeholder_image', models.ImageField(blank=True, help_text='Placeholder image shown when video is not playing (recommended: 1920x1080px)', null=True, upload_to='homepage/video/')),
                ('background_image_left', models.ImageField(blank=True, help_text='Left background decoration image', null=True, upload_to='homepage/video/backgrounds/')),
                ('background_image_right', models.ImageField(blank=True, help_text='Right background decoration image', null=True, upload_to='homepage/video/backgrounds/')),
                ('is_active', models.BooleanField(default=True, help_text='Show video showcase on homepage')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Video Showcase',
                'verbose_name_plural': 'Video Showcase',
                'ordering': ['-created_at'],
            },
        ),
    ]
