# Generated by Django 5.2.6 on 2025-09-25 22:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0010_videoshowcase'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videoshowcase',
            name='background_image_left',
        ),
        migrations.RemoveField(
            model_name='videoshowcase',
            name='background_image_right',
        ),
    ]
