# Generated by Django 5.2.6 on 2025-09-25 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0011_remove_videoshowcase_background_image_left_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='videoshowcase',
            options={'ordering': ['-created_at'], 'verbose_name': 'Video Showcase', 'verbose_name_plural': 'Video Showcases'},
        ),
        migrations.RemoveField(
            model_name='videoshowcase',
            name='placeholder_image',
        ),
        migrations.RemoveField(
            model_name='videoshowcase',
            name='youtube_url',
        ),
        migrations.AddField(
            model_name='videoshowcase',
            name='alt_text',
            field=models.CharField(default='Wedding video showcase', help_text='Alt text for accessibility', max_length=200),
        ),
        migrations.AddField(
            model_name='videoshowcase',
            name='autoplay',
            field=models.BooleanField(default=True, help_text='Auto-play video when in view'),
        ),
        migrations.AddField(
            model_name='videoshowcase',
            name='loop_video',
            field=models.BooleanField(default=True, help_text='Loop video playback'),
        ),
        migrations.AddField(
            model_name='videoshowcase',
            name='mute_audio',
            field=models.BooleanField(default=True, help_text='Mute video audio'),
        ),
        migrations.AddField(
            model_name='videoshowcase',
            name='show_controls',
            field=models.BooleanField(default=False, help_text='Show video player controls'),
        ),
        migrations.AddField(
            model_name='videoshowcase',
            name='thumbnail_image',
            field=models.ImageField(blank=True, help_text='Custom thumbnail image (optional - will use YouTube thumbnail if not provided)', null=True, upload_to='videos/thumbnails/'),
        ),
        migrations.AddField(
            model_name='videoshowcase',
            name='youtube_video_id',
            field=models.CharField(default='', help_text='YouTube video ID (from URL: https://www.youtube.com/watch?v=VIDEO_ID)', max_length=50),
        ),
        migrations.AlterField(
            model_name='videoshowcase',
            name='description',
            field=models.TextField(blank=True, help_text='Video description'),
        ),
        migrations.AlterField(
            model_name='videoshowcase',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Show this video on website'),
        ),
        migrations.AlterField(
            model_name='videoshowcase',
            name='title',
            field=models.CharField(help_text="Video title (e.g., 'Wedding Cinematic Reel')", max_length=200),
        ),
    ]
