# Generated by Django 5.2.6 on 2025-10-16 23:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0012_alter_videoshowcase_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ShowcaseImage',
        ),
    ]
