# Generated by Django 5.2.6 on 2025-10-17 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0013_delete_showcaseimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='heroslide',
            name='order',
            field=models.PositiveIntegerField(default=0, editable=False, help_text='Auto-managed ordering (based on creation time)'),
        ),
    ]
