# Generated by Django 5.2.6 on 2025-10-17 04:35

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StaticPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Page title', max_length=200)),
                ('slug', models.SlugField(blank=True, help_text='URL-friendly version of title', max_length=220, unique=True)),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(help_text='Rich content with support for images and formatted text')),
                ('meta_title', models.CharField(blank=True, help_text='SEO title (60 chars max)', max_length=60)),
                ('meta_description', models.CharField(blank=True, help_text='SEO description (160 chars max)', max_length=160)),
                ('meta_keywords', models.CharField(blank=True, help_text='Comma-separated keywords', max_length=255)),
                ('is_published', models.BooleanField(default=True, help_text='Show/hide page')),
                ('show_in_footer', models.BooleanField(default=True, help_text='Display link in footer')),
                ('display_order', models.PositiveIntegerField(default=0, help_text='Order in footer (lower number = higher position)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Static Page',
                'verbose_name_plural': 'Static Pages',
                'ordering': ['display_order', 'title'],
                'indexes': [models.Index(fields=['slug'], name='staticpages_slug_4da043_idx'), models.Index(fields=['is_published'], name='staticpages_is_publ_81a08a_idx'), models.Index(fields=['show_in_footer', 'display_order'], name='staticpages_show_in_950df1_idx')],
            },
        ),
    ]
