"""
Django settings for chobighar_backend project.

Generated by 'django-admin startproject' using Django 5.2.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
import os
from decouple import config

SECRET_KEY = config('DJANGO_SECRET_KEY', default='django-insecure-+4f7g_f82qx$+g#1^*c%1e4dc^-g%eogd_ntht7jewx8d@u8k+')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config('DJANGO_DEBUG', default=True, cast=bool)

# Environment-aware allowed hosts
ALLOWED_HOSTS = [
    'admin.chobighar.com',
    'www.admin.chobighar.com', 
    'chobighar.com',
    'www.chobighar.com',
    '127.0.0.1',
    'localhost',
    '*'  # Remove this in production
]


# Application definition

INSTALLED_APPS = [
    'jazzmin',  # Must be before django.contrib.admin
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'corsheaders',
    'django_filters',
    'header',
    'footer',
    'contact',
    'homepage',
    'aboutpage',
    'photoshootpage',
    'portfolio',
    'vendor',
    'search',
    'inquiry',
    'blog',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',  # For serving static files
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'chobighar_backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'chobighar_backend.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Kolkata'  # Set to India timezone for Kolkata business

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'

# Additional locations of static files
STATICFILES_DIRS = [
    BASE_DIR / "static",
]

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# CORS settings - Environment-aware configuration
CORS_ALLOWED_ORIGINS = [
    "https://chobighar.com",
    "https://www.chobighar.com",
    "https://admin.chobighar.com",
    "https://www.admin.chobighar.com",
    "http://localhost:3000",  # Development
    "http://127.0.0.1:3000",  # Development
]

# Add custom CORS origins from environment if specified
CUSTOM_CORS_ORIGINS = config('CORS_ALLOWED_ORIGINS', default='')
if CUSTOM_CORS_ORIGINS:
    CORS_ALLOWED_ORIGINS.extend([origin.strip() for origin in CUSTOM_CORS_ORIGINS.split(',')])

# Additional CORS settings for production
CORS_ALLOW_CREDENTIALS = True
CORS_ALLOW_ALL_ORIGINS = False

# REST Framework settings
REST_FRAMEWORK = {
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.AllowAny',
    ],
    'DEFAULT_RENDERER_CLASSES': [
        'rest_framework.renderers.JSONRenderer',
    ],
}

# Media files
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Static files for production
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Jazzmin Admin Theme Configuration
JAZZMIN_SETTINGS = {
    # title of the window (Will default to current_admin_site.site_title if absent or None)
    "site_title": "chobighar Admin",

    # Title on the login screen (19 chars max) (defaults to current_admin_site.site_header if absent or None)
    "site_header": "chobighar",

    # Title on the brand (19 chars max) (defaults to current_admin_site.site_header if absent or None)
    "site_brand": "chobighar Admin",

    # Logo to use for your site, must be present in static files, used for brand on top left
    "site_logo": "admin/img/chobighar.png",

    # Logo to use for your site, must be present in static files, used for login form logo (defaults to site_logo)
    "login_logo": "admin/img/chobighar.png",

    # CSS classes that are applied to the logo above
    "site_logo_classes": "img-circle chobighar-logo-small",

    # Relative path to a favicon for your site, will default to site_logo if absent (ideally 32x32 px)
    "site_icon": "admin/img/chobighar.png",

    # Welcome text on the login screen
    "welcome_sign": "Welcome to chobighar Admin",

    # Copyright on the footer
    "copyright": "chobighar Photography & Events",

    # List of model admins to search from the search bar, search bar omitted if excluded
    "search_model": ["auth.User", "inquiry.Inquiry", "vendor.Vendor", "portfolio.Portfolio"],

    # Field name on user model that contains avatar ImageField/URLField/Charfield or a callable that receives the user
    "user_avatar": None,

    ############
    # Top Menu #
    ############

    # Links to put along the top menu
    "topmenu_links": [
        # Url that gets reversed (Permissions can be added)
        {"name": "Home", "url": "admin:index", "permissions": ["auth.view_user"]},
        # external url that opens in a new window (Permissions can be added)
        {"name": "View Main Site", "url": "https://chobighar.com", "new_window": True},
        {"name": "View Local Dev", "url": "http://localhost:3000", "new_window": True},
        # model admin to link to (Permissions checked against model)
        {"model": "inquiry.Inquiry"},
        # App with dropdown menu to all its models pages (Permissions checked against models)
        {"app": "vendor"},
    ],

    #############
    # User Menu #
    #############

    # Additional links to include in the user menu on the top right ("app" url type is not allowed)
    "usermenu_links": [
        {"name": "View Main Site", "url": "https://chobighar.com", "new_window": True},
        {"name": "View Local Dev", "url": "http://localhost:3000", "new_window": True},
        {"model": "auth.user"}
    ],

    #############
    # Side Menu #
    #############

    # Whether to display the side menu
    "show_sidebar": True,

    # Whether to aut expand the menu
    "navigation_expanded": True,

    # Hide these apps when generating side menu e.g (auth)
    "hide_apps": [],

    # Hide these models when generating side menu (e.g auth.user)
    "hide_models": [],

    # List of apps (and/or models) to base side menu ordering off of (does not need to contain all apps/models)
    "order_with_respect_to": ["inquiry", "vendor", "portfolio", "homepage", "header", "footer", "contact", "aboutpage", "photoshootpage", "auth"],

    # Custom links to append to app groups, keyed on app name for the app group
    "custom_links": {
        "inquiry": [{
            "name": "View All Inquiries", 
            "url": "admin:inquiry_inquiry_changelist", 
            "icon": "fas fa-envelope",
            "permissions": ["inquiry.view_inquiry"]
        }],
        "vendor": [{
            "name": "Add New Vendor", 
            "url": "admin:vendor_vendor_add", 
            "icon": "fas fa-plus",
            "permissions": ["vendor.add_vendor"]
        }],
        "portfolio": [{
            "name": "Add New Portfolio", 
            "url": "admin:portfolio_portfolio_add", 
            "icon": "fas fa-plus",
            "permissions": ["portfolio.add_portfolio"]
        }]
    },

    # Custom icons for side menu apps/models
    "icons": {
        "auth": "fas fa-users-cog",
        "auth.user": "fas fa-user",
        "auth.Group": "fas fa-users",
        "inquiry": "fas fa-envelope",
        "inquiry.Inquiry": "fas fa-envelope-open",
        "inquiry.InquiryFollowUp": "fas fa-reply",
        "vendor": "fas fa-store",
        "vendor.Vendor": "fas fa-store-alt",
        "vendor.VendorCategory": "fas fa-tags",
        "vendor.VendorSubcategory": "fas fa-tag",
        "vendor.VendorImage": "fas fa-images",
        "portfolio": "fas fa-camera",
        "portfolio.Portfolio": "fas fa-camera-retro",
        "portfolio.PortfolioImage": "fas fa-image",
        "portfolio.PortfolioVideo": "fas fa-video",
        "portfolio.Category": "fas fa-folder",
        "homepage": "fas fa-home",
        "header": "fas fa-header",
        "footer": "fas fa-footer",
        "contact": "fas fa-address-book",
        "aboutpage": "fas fa-info-circle",
        "photoshootpage": "fas fa-camera",
    },

    # Icons that are used when one is not manually specified
    "default_icon_parents": "fas fa-chevron-circle-right",
    "default_icon_children": "fas fa-circle",

    #################
    # Related Modal #
    #################
    # Use modals instead of popups
    "related_modal_active": False,

    #############
    # UI Tweaks #
    #############
    # Relative paths to custom CSS/JS scripts (must be present in static files)
    "custom_css": "admin/css/custom_admin.css",
    "custom_js": "admin/js/custom_admin.js",
    # Whether to link font from fonts.googleapis.com (use custom_css to supply font otherwise)
    "use_google_fonts_cdn": True,
    # Whether to show the UI customizer on the sidebar
    "show_ui_builder": True,

    ###############
    # Change view #
    ###############
    # Render out the change view as a single form, or in tabs, current options are
    # - single
    # - horizontal_tabs (default)
    # - vertical_tabs
    # - collapsible
    # - carousel
    "changeform_format": "horizontal_tabs",
    # override change forms on a per modeladmin basis
    "changeform_format_overrides": {"auth.user": "collapsible", "auth.group": "vertical_tabs"},
    # Add a language dropdown into the admin
    "language_chooser": False,
}

JAZZMIN_UI_TWEAKS = {
    "navbar_small_text": False,
    "footer_small_text": False,
    "body_small_text": False,
    "brand_small_text": False,
    "brand_colour": "navbar-danger",  # Red theme for chobighar branding
    "accent": "accent-danger",
    "navbar": "navbar-danger navbar-dark",
    "no_navbar_border": False,
    "navbar_fixed": True,
    "layout_boxed": False,
    "footer_fixed": False,
    "sidebar_fixed": True,
    "sidebar": "sidebar-dark-danger",
    "sidebar_nav_small_text": False,
    "sidebar_disable_expand": False,
    "sidebar_nav_child_indent": False,
    "sidebar_nav_compact_style": False,
    "sidebar_nav_legacy_style": False,
    "sidebar_nav_flat_style": False,
    "theme": "lux",  # Professional theme
    "dark_mode_theme": None,
    "button_classes": {
        "primary": "btn-danger",  # Red primary buttons for consistency
        "secondary": "btn-secondary",
        "info": "btn-info", 
        "warning": "btn-warning",
        "danger": "btn-danger",
        "success": "btn-success"
    }
}

# Security settings
SECURE_BROWSER_XSS_FILTER = True
SECURE_CONTENT_TYPE_NOSNIFF = True
X_FRAME_OPTIONS = 'DENY'

# Production security settings (uncomment when SSL is configured)
if not DEBUG:
    SECURE_SSL_REDIRECT = False  # Set to True when SSL is enabled
    SESSION_COOKIE_SECURE = False  # Set to True when SSL is enabled
    CSRF_COOKIE_SECURE = False  # Set to True when SSL is enabled
    # SECURE_HSTS_SECONDS = 31536000
    # SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    # SECURE_HSTS_PRELOAD = True

# Logging configuration
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {process:d} {thread:d} {message}',
            'style': '{',
        },
        'simple': {
            'format': '{levelname} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'file': {
            'level': 'INFO',
            'class': 'logging.FileHandler',
            'filename': BASE_DIR / 'logs' / 'django.log',
            'formatter': 'verbose',
        },
        'console': {
            'level': 'DEBUG' if DEBUG else 'INFO',
            'class': 'logging.StreamHandler',
            'formatter': 'simple',
        },
    },
    'root': {
        'handlers': ['console'],
        'level': 'INFO',
    },
    'loggers': {
        'django': {
            'handlers': ['console', 'file'] if not DEBUG else ['console'],
            'level': 'INFO',
            'propagate': False,
        },
    },
}

# Create logs directory if it doesn't exist
import os
os.makedirs(BASE_DIR / 'logs', exist_ok=True)
