# Generated by Django 5.2.4 on 2025-09-26 17:16

import portfolio.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolio',
            name='cover_image',
        ),
        migrations.RemoveField(
            model_name='portfolioimage',
            name='image',
        ),
        migrations.AddField(
            model_name='portfolio',
            name='cover_image_file',
            field=models.ImageField(blank=True, help_text='Upload cover image file', null=True, upload_to=portfolio.models.portfolio_cover_upload_to),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='cover_image_url',
            field=models.URLField(blank=True, help_text='Or provide cover image URL', max_length=500),
        ),
        migrations.AddField(
            model_name='portfolioimage',
            name='image_file',
            field=models.ImageField(blank=True, help_text='Upload image file', null=True, upload_to=portfolio.models.portfolio_image_upload_to),
        ),
        migrations.AddField(
            model_name='portfolioimage',
            name='image_url',
            field=models.URLField(blank=True, help_text='Or provide image URL', max_length=500),
        ),
        migrations.AddField(
            model_name='portfoliovideo',
            name='thumbnail_file',
            field=models.ImageField(blank=True, help_text='Upload custom thumbnail', null=True, upload_to=portfolio.models.portfolio_video_thumbnail_upload_to),
        ),
        migrations.AlterField(
            model_name='portfoliovideo',
            name='thumbnail_url',
            field=models.URLField(blank=True, help_text='Or provide thumbnail URL', max_length=500),
        ),
    ]
