# Generated by Django 5.2.6 on 2025-10-08 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_remove_portfolio_cover_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='meta_description',
            field=models.TextField(blank=True, help_text='SEO description (leave blank to auto-generate from description)', max_length=320),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='meta_keywords',
            field=models.CharField(blank=True, help_text="SEO keywords, comma-separated (e.g., 'wedding photography, Kolkata, pre-wedding shoot')", max_length=500),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='meta_title',
            field=models.CharField(blank=True, help_text='SEO title (leave blank to auto-generate from title)', max_length=200),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='og_image',
            field=models.ImageField(blank=True, help_text='Open Graph image for social media sharing (1200x630px recommended)', null=True, upload_to='portfolio/og_images/'),
        ),
    ]
