# Generated by Django 5.2.6 on 2025-10-16 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_portfolio_meta_description_portfolio_meta_keywords_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfoliovideo',
            name='thumbnail_file',
        ),
        migrations.RemoveField(
            model_name='portfoliovideo',
            name='thumbnail_url',
        ),
    ]
