# Generated by Django 5.2.6 on 2025-10-16 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_remove_video_thumbnails'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='cta_image_1',
            field=models.ImageField(blank=True, help_text='CTA section image 1 (top-left)', null=True, upload_to='portfolio/cta/'),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='cta_image_2',
            field=models.ImageField(blank=True, help_text='CTA section image 2 (top-right)', null=True, upload_to='portfolio/cta/'),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='cta_image_3',
            field=models.ImageField(blank=True, help_text='CTA section image 3 (bottom-left)', null=True, upload_to='portfolio/cta/'),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='cta_image_4',
            field=models.ImageField(blank=True, help_text='CTA section image 4 (bottom-right)', null=True, upload_to='portfolio/cta/'),
        ),
    ]
