# Generated by Django 5.2.6 on 2025-10-16 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_portfolio_cta_image_1_portfolio_cta_image_2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='promotional_video_id',
            field=models.CharField(blank=True, help_text="YouTube Video ID (e.g., 'dQw4w9WgXcQ') - Video will autoplay, loop, and be muted in mobile mockup", max_length=100),
        ),
    ]
