# Generated by Django 5.2.6 on 2025-10-16 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0006_portfolio_promotional_video_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolioimage',
            name='featured',
            field=models.BooleanField(default=False, help_text='Show in homepage gallery and portfolio page'),
        ),
    ]
