# Generated by Django 5.2.6 on 2025-10-16 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0007_portfolioimage_featured'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfoliovideo',
            name='duration',
        ),
        migrations.AddField(
            model_name='portfoliovideo',
            name='featured',
            field=models.BooleanField(default=False, help_text='Show in featured wedding videos section'),
        ),
    ]
