# Generated by Django 5.2.6 on 2025-10-17 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0008_remove_portfoliovideo_duration_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='order',
            field=models.PositiveIntegerField(default=0, editable=False, help_text='Auto-managed ordering (based on creation time)'),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='order',
            field=models.PositiveIntegerField(default=0, editable=False, help_text='Auto-managed ordering (based on creation time)'),
        ),
        migrations.AlterField(
            model_name='portfoliohighlight',
            name='order',
            field=models.PositiveIntegerField(default=0, editable=False, help_text='Auto-managed ordering (based on creation time)'),
        ),
        migrations.AlterField(
            model_name='portfolioimage',
            name='order',
            field=models.PositiveIntegerField(default=0, editable=False, help_text='Auto-managed ordering (based on creation time)'),
        ),
        migrations.AlterField(
            model_name='portfolioservice',
            name='order',
            field=models.PositiveIntegerField(default=0, editable=False, help_text='Auto-managed ordering (based on creation time)'),
        ),
        migrations.AlterField(
            model_name='portfoliovideo',
            name='order',
            field=models.PositiveIntegerField(default=0, editable=False, help_text='Auto-managed ordering (based on creation time)'),
        ),
    ]
