# Generated by Django 5.2.6 on 2025-10-17 00:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0009_alter_category_order_alter_portfolio_order_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PortfolioInquiry',
        ),
    ]
