# Generated by Django 5.2.6 on 2025-10-17 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0010_delete_portfolioinquiry'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='love_count',
            field=models.PositiveIntegerField(default=0, help_text='Number of love reactions (auto-incremented by users)'),
        ),
    ]
