# Generated by Django 5.2.4 on 2025-09-26 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photoshootpage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhotoshootTestimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(help_text="Client name (e.g., 'Priya & Arjun' or 'Sneha Sharma')", max_length=100)),
                ('service_type', models.CharField(help_text="Service received (e.g., 'Bengali Wedding Photography', 'Portrait Session')", max_length=100)),
                ('rating', models.PositiveIntegerField(choices=[(1, '1 Star'), (2, '2 Stars'), (3, '3 Stars'), (4, '4 Stars'), (5, '5 Stars')], default=5, help_text='Rating out of 5 stars')),
                ('testimonial_text', models.TextField(help_text="Client's review/testimonial")),
                ('client_image', models.ImageField(blank=True, help_text='Client photo (recommended: square image, 100x100px minimum)', null=True, upload_to='photoshoot/testimonials/')),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order (lower numbers first)')),
                ('is_active', models.BooleanField(default=True, help_text='Show this testimonial')),
                ('is_featured', models.BooleanField(default=False, help_text='Feature this testimonial on homepage')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Photoshoot Testimonial',
                'verbose_name_plural': 'Photoshoot Testimonials',
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
