# Generated by Django 5.2.6 on 2025-09-25 19:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactTestimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Client name', max_length=100)),
                ('service', models.CharField(help_text='Service they used', max_length=100)),
                ('rating', models.PositiveIntegerField(default=5, help_text='Rating out of 5')),
                ('comment', models.TextField(help_text='Testimonial comment')),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order (lower numbers first)')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Contact Testimonial',
                'verbose_name_plural': 'Contact Testimonials',
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='ContactUsHero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_image', models.ImageField(blank=True, help_text='Hero section background image', null=True, upload_to='contact/hero/')),
                ('main_title', models.CharField(default="Let's Create Something Beautiful", help_text='Main hero title', max_length=200)),
                ('subtitle', models.CharField(default='Ready to capture your precious moments? Get in touch with our creative team', help_text='Hero subtitle text', max_length=300)),
                ('description', models.TextField(default="Ready to capture your precious moments? Get in touch with our creative team and let's discuss how we can bring your vision to life with our signature Bengali artistry.", help_text='Hero description text')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Contact Us Hero',
                'verbose_name_plural': 'Contact Us Hero',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ContactUsInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primary_phone', models.CharField(default='+91 96479 66765', max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('secondary_phone', models.CharField(blank=True, max_length=17, null=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('primary_email', models.EmailField(default='booking@chobighar.com', max_length=254)),
                ('secondary_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('whatsapp_number', models.CharField(default='+91 96479 66765', max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('address_line1', models.CharField(default='Sector 5, Salt Lake City', max_length=200)),
                ('address_line2', models.CharField(default='Kolkata, West Bengal 700091', max_length=200)),
                ('city', models.CharField(default='Kolkata', max_length=100)),
                ('state', models.CharField(default='West Bengal', max_length=100)),
                ('postal_code', models.CharField(default='700091', max_length=20)),
                ('country', models.CharField(default='India', max_length=100)),
                ('weekday_hours', models.CharField(default='Mon - Sat: 10 AM - 7 PM', max_length=100)),
                ('weekend_hours', models.CharField(default='Sun: 11 AM - 5 PM', max_length=100)),
                ('emergency_note', models.CharField(default='Emergency shoots available', max_length=200)),
                ('phone_label', models.CharField(default='Call Us', max_length=50)),
                ('email_label', models.CharField(default='Email Us', max_length=50)),
                ('address_label', models.CharField(default='Visit Us', max_length=50)),
                ('hours_label', models.CharField(default='Office Hours', max_length=50)),
                ('phone_description', models.CharField(default='Available 9 AM - 9 PM', max_length=100)),
                ('email_description', models.CharField(default='We respond within 24 hours', max_length=100)),
                ('address_description', models.CharField(default='By appointment only', max_length=100)),
                ('google_map_url', models.URLField(blank=True, default='https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3684.0929455463855!2d88.36320731495713!3d22.576484185188667!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x3a027579f4b6c5e3%3A0x5d9f4a1a5d9e8a1a!2sSector%20V%2C%20Bidhannagar%2C%20Kolkata%2C%20West%20Bengal%20700091!5e0!3m2!1sen!2sin!4v1635746400000!5m2!1sen!2sin', help_text='Google Maps embed URL for location', null=True)),
                ('map_height', models.PositiveIntegerField(default=400, help_text='Map height in pixels')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Contact Us Info',
                'verbose_name_plural': 'Contact Us Info',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WhyChooseUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Why Choose chobighar?', max_length=200)),
                ('point', models.CharField(help_text='A reason why clients should choose us', max_length=300)),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order (lower numbers first)')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Why Choose Us Point',
                'verbose_name_plural': 'Why Choose Us Points',
                'ordering': ['order', 'created_at'],
            },
        ),
    ]
