# Generated by Django 5.2.6 on 2025-09-25 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='whychooseus',
            name='title',
        ),
    ]
