# Generated by Django 5.2.6 on 2025-09-25 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('footer', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FooterQuickLinks',
        ),
        migrations.DeleteModel(
            name='FooterServices',
        ),
    ]
