# Generated by Django 5.2.6 on 2025-10-15 14:11

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(help_text='Rich content with support for images, videos, and formatted text'),
        ),
    ]
