# Generated by Django 5.2.6 on 2025-09-25 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('header', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('url', models.URLField()),
                ('icon_class', models.CharField(help_text='CSS class for the icon', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order')),
            ],
            options={
                'verbose_name': 'Social Media',
                'verbose_name_plural': 'Social Media Links',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.DeleteModel(
            name='SocialIcon',
        ),
        migrations.AlterModelOptions(
            name='brandinfo',
            options={'verbose_name': 'Brand Info', 'verbose_name_plural': 'Brand Information'},
        ),
        migrations.AlterModelOptions(
            name='contactinfo',
            options={'verbose_name': 'Contact Info', 'verbose_name_plural': 'Contact Information'},
        ),
        migrations.RemoveField(
            model_name='brandinfo',
            name='logo',
        ),
        migrations.AddField(
            model_name='brandinfo',
            name='logo_image',
            field=models.ImageField(blank=True, null=True, upload_to='brand/'),
        ),
    ]
