# Generated by Django 5.2.6 on 2025-09-25 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('header', '0002_socialmedia_delete_socialicon_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='socialmedia',
            name='icon_class',
        ),
        migrations.AlterField(
            model_name='socialmedia',
            name='name',
            field=models.CharField(choices=[('instagram', 'Instagram'), ('facebook', 'Facebook'), ('youtube', 'YouTube'), ('x', 'X (Twitter)'), ('pinterest', 'Pinterest'), ('linkedin', 'LinkedIn')], max_length=20, unique=True),
        ),
    ]
