# Generated by Django 5.2.6 on 2025-09-25 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('header', '0003_remove_socialmedia_icon_class_alter_socialmedia_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='FooterInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(default='Professional photography and videography services capturing your most precious moments with artistic excellence and cultural authenticity.', help_text='Company description text')),
                ('address_line1', models.CharField(default='Kolkata, West Bengal', max_length=100)),
                ('address_line2', models.CharField(default='India', max_length=100)),
                ('phone', models.CharField(default='+91 96479 66765', max_length=20)),
                ('email', models.EmailField(default='info@chobighar.com', max_length=254)),
                ('whatsapp_number', models.CharField(default='+91 96479 66765', max_length=20)),
                ('weekday_hours', models.CharField(default='Mon - Sat: 9:00 AM - 8:00 PM', max_length=50)),
                ('weekend_hours', models.CharField(default='Sunday: By Appointment', max_length=50)),
                ('whatsapp_text', models.CharField(default='Quick Response', max_length=50)),
                ('email_text', models.CharField(default='24/7 Support', max_length=50)),
                ('phone_text', models.CharField(default='Mon - Sat: 9 AM - 8 PM', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Footer Info',
                'verbose_name_plural': 'Footer Information',
            },
        ),
    ]
