# Generated by Django 5.2.6 on 2025-09-25 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('header', '0004_footerinfo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FooterInfo',
        ),
    ]
