# Generated by Django 5.2.6 on 2025-10-02 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('header', '0005_delete_footerinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactinfo',
            name='whatsapp_number',
            field=models.CharField(blank=True, help_text='WhatsApp number for sticky WhatsApp button', max_length=20, null=True),
        ),
    ]
