# Generated by Django 5.2.6 on 2025-10-02 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('header', '0006_contactinfo_whatsapp_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialmedia',
            name='name',
            field=models.CharField(choices=[('instagram', 'Instagram'), ('facebook', 'Facebook'), ('youtube', 'YouTube'), ('x', 'X (Twitter)'), ('pinterest', 'Pinterest'), ('linkedin', 'LinkedIn'), ('whatsapp', 'WhatsApp')], max_length=20, unique=True),
        ),
    ]
