# Generated by Django 5.2.6 on 2025-10-02 00:55

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inquiry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('inquiry_type', models.CharField(choices=[('photoshoot', 'Photoshoot Service'), ('vendor', 'Vendor Service'), ('portfolio', 'Portfolio Inquiry'), ('general', 'General Inquiry'), ('quote', 'Quote Request')], default='general', help_text='Type of inquiry', max_length=20)),
                ('name', models.CharField(help_text="Customer's full name", max_length=100)),
                ('email', models.EmailField(help_text="Customer's email address", max_length=254)),
                ('phone', models.CharField(help_text="Customer's phone number", max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('subject', models.CharField(help_text='Subject of inquiry', max_length=200)),
                ('message', models.TextField(help_text='Detailed message from customer')),
                ('service_name', models.CharField(blank=True, help_text='Name of service inquired about', max_length=200, null=True)),
                ('service_id', models.CharField(blank=True, help_text='ID of service/vendor/portfolio inquired about', max_length=50, null=True)),
                ('event_date', models.DateField(blank=True, help_text='Date of event/photoshoot', null=True)),
                ('event_location', models.CharField(blank=True, help_text='Location of event/photoshoot', max_length=200, null=True)),
                ('budget_range', models.CharField(blank=True, help_text="Customer's budget range", max_length=100, null=True)),
                ('status', models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='new', help_text='Current status of inquiry', max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', help_text='Priority level', max_length=10)),
                ('assigned_to', models.CharField(blank=True, help_text='Staff member assigned to handle this inquiry', max_length=100, null=True)),
                ('source', models.CharField(default='website', help_text='Source of inquiry (website, social media, etc.)', max_length=50)),
                ('notes', models.TextField(blank=True, help_text='Internal notes about this inquiry', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('responded_at', models.DateTimeField(blank=True, help_text='When the inquiry was first responded to', null=True)),
            ],
            options={
                'verbose_name': 'Inquiry',
                'verbose_name_plural': 'Inquiries',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InquiryFollowUp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('follow_up_date', models.DateTimeField(help_text='Date and time of follow-up')),
                ('method', models.CharField(choices=[('phone', 'Phone Call'), ('email', 'Email'), ('whatsapp', 'WhatsApp'), ('meeting', 'In-Person Meeting'), ('video_call', 'Video Call')], help_text='Method of follow-up', max_length=20)),
                ('notes', models.TextField(help_text='Notes from the follow-up')),
                ('staff_member', models.CharField(help_text='Staff member who did the follow-up', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('inquiry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followups', to='inquiry.inquiry')),
            ],
            options={
                'verbose_name': 'Follow-up',
                'verbose_name_plural': 'Follow-ups',
                'ordering': ['-follow_up_date'],
            },
        ),
    ]
